version: '2'
services:
    php:
        container_name: sf_php
        image: php:7.1-fpm
        volumes:
            - ./symfony:/var/www/symfony
        links:
            - mysql
    nginx:
        container_name: sf_nginx
        image: nginx:stable
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    mysql:
        container_name: sf_mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
            - "3306:3306"
