version: '2'
services:
    php:
        image: php:7.1-fpm
        volumes:
            - ./app:/var/www/app
    nginx:
        container_name: nginx
        image: nginx:stable
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
