version: '2'
services:
    php:
        container_name: php
        build: ./docker/php
        volumes:
            - ./app:/var/www/app
        links:
            - mysql
    nginx:
        container_name: nginx
        image: nginx:stable
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    mysql:
        container_name: mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: app
        ports:
            - "3306:3306"
